
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  6 2025 15:48:16 WET (Jan  6 2025 15:48:16 UTC)

// Verification Directory fv/BATCHARGERctr 

module BATCHARGERctr(cc, tc, cv, imonen, vmonen, tmonen, so, vbat,
     ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend, clk,
     en, rstz, vtok, dvdd, dgnd);
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  input clk, en, rstz, vtok, dvdd, dgnd;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire clk, en, rstz, vtok, dvdd, dgnd;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire [2:0] state;
  wire [15:0] charge_timer;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, logic_1_1_net;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_265;
  assign imonen = cv;
  DBFRSBEHD tmonen_reg_reg(.RB (logic_1_1_net), .SB (rstz), .CKB (clk),
       .D (n_265), .Q (tmonen), .QB (UNCONNECTED));
  DBFRBEHD cc_reg_reg(.RB (rstz), .CKB (clk), .D (n_264), .Q (cc), .QB
       (UNCONNECTED0));
  DBFRBEHD cv_reg_reg(.RB (rstz), .CKB (clk), .D (n_263), .Q (cv), .QB
       (UNCONNECTED1));
  DBFRBEHD tc_reg_reg(.RB (rstz), .CKB (clk), .D (n_260), .Q (tc), .QB
       (UNCONNECTED2));
  MUX2CHD g9160__2398(.S (n_257), .A (tmonen), .B (n_254), .O (n_265));
  DBFRBEHD \state_reg[0] (.RB (rstz), .CKB (clk), .D (n_258), .Q
       (state[0]), .QB (UNCONNECTED3));
  OAI13BHD g9163__5107(.A1 (n_73), .B1 (n_255), .B2 (n_262), .B3
       (n_261), .O (n_264));
  OAI13BHD g9165__6260(.A1 (n_80), .B1 (n_259), .B2 (n_262), .B3
       (n_261), .O (n_263));
  DBFRBEHD \state_reg[1] (.RB (rstz), .CKB (clk), .D (n_256), .Q
       (state[1]), .QB (UNCONNECTED4));
  OAI13BHD g9164__4319(.A1 (n_77), .B1 (n_259), .B2 (n_253), .B3
       (n_261), .O (n_260));
  OAI22CHD g9168__8428(.A1 (n_261), .A2 (n_262), .B1 (n_243), .B2
       (n_257), .O (n_258));
  OAI22CHD g9167__5526(.A1 (n_261), .A2 (n_255), .B1 (n_240), .B2
       (n_257), .O (n_256));
  OR2B1CHD g9169__6783(.I1 (n_255), .B1 (n_262), .O (n_254));
  DBFRBEHD \state_reg[2] (.RB (rstz), .CKB (clk), .D (n_251), .Q
       (state[2]), .QB (UNCONNECTED5));
  INVCKDHD g9172(.I (n_253), .O (n_262));
  ND3CHD g9171__3680(.I1 (n_249), .I2 (n_247), .I3 (n_252), .O (n_255));
  OAI12CHD g9173__1617(.A1 (n_250), .B1 (state[2]), .B2 (n_252), .O
       (n_253));
  OAI22CHD g9170__2802(.A1 (n_261), .A2 (n_259), .B1 (n_244), .B2
       (n_257), .O (n_251));
  AOI22BHD g9175__1705(.A1 (n_246), .A2 (n_234), .B1 (n_45), .B2
       (n_239), .O (n_250));
  AOI13BHD g9176__5122(.A1 (n_248), .B1 (state[2]), .B2 (state[0]), .B3
       (n_242), .O (n_249));
  NR2CHD g9177__8246(.I1 (n_241), .I2 (n_181), .O (n_248));
  OR3B2CHD g9174__7098(.I1 (n_245), .B1 (n_247), .B2 (n_252), .O
       (n_259));
  OAI22CHD g9179__6131(.A1 (n_216), .A2 (n_235), .B1 (state[2]), .B2
       (n_247), .O (n_246));
  OAI13BHD g9178__1881(.A1 (n_238), .B1 (n_244), .B2 (n_243), .B3
       (n_242), .O (n_245));
  OA13EHD g9181__5115(.A1 (n_237), .B1 (n_243), .B2 (n_240), .B3
       (n_231), .O (n_241));
  OAI112BHD g9180__7482(.A1 (n_247), .B1 (n_252), .C1 (n_243), .C2
       (n_233), .O (n_239));
  AOI22BHD g9182__4733(.A1 (n_221), .A2 (n_227), .B1 (n_243), .B2
       (n_236), .O (n_238));
  OR2B1CHD g9183__6161(.I1 (n_236), .B1 (n_229), .O (n_237));
  AOI13BHD g9184__9315(.A1 (n_232), .B1 (n_244), .B2 (n_228), .B3
       (n_230), .O (n_235));
  ND2DHD g9185__9945(.I1 (state[0]), .I2 (n_233), .O (n_234));
  OA112EHD g9186__2883(.A1 (n_240), .B1 (n_231), .C1 (state[2]), .C2
       (n_230), .O (n_232));
  OAI112BHD g9188__2346(.A1 (n_231), .B1 (n_226), .C1 (state[0]), .C2
       (n_228), .O (n_229));
  NR2CHD g9189__1666(.I1 (n_242), .I2 (n_244), .O (n_233));
  OR2EHD g9190__7410(.I1 (n_226), .I2 (n_231), .O (n_227));
  OAI22CHD g9192__6417(.A1 (n_225), .A2 (state[1]), .B1 (n_240), .B2
       (n_228), .O (n_226));
  AOI112BHD g9193__5477(.A1 (n_223), .B1 (n_166), .C1 (n_43), .C2
       (iend[7]), .O (n_242));
  AOI22BHD g9195__2398(.A1 (n_244), .A2 (n_228), .B1 (state[2]), .B2
       (n_225), .O (n_231));
  DBFRBEHD \charge_timer_reg[15] (.RB (rstz), .CKB (clk), .D (n_224),
       .Q (charge_timer[15]), .QB (UNCONNECTED6));
  AO22CHD g9202__5107(.A1 (charge_timer[15]), .A2 (n_219), .B1
       (charge_timer[13]), .B2 (n_200), .O (n_224));
  INVCKDHD g9201(.I (n_225), .O (n_228));
  OAI112BHD g9198__6260(.A1 (n_220), .B1 (n_82), .C1 (n_105), .C2
       (n_165), .O (n_223));
  DBFRBEHD \charge_timer_reg[14] (.RB (rstz), .CKB (clk), .D (n_222),
       .Q (charge_timer[14]), .QB (UNCONNECTED7));
  MAO222EHD g9203__4319(.A1 (n_217), .B1 (n_72), .C1 (n_97), .O
       (n_225));
  OAI13BHD g9206__8428(.A1 (n_218), .B1 (n_214), .B2
       (charge_timer[14]), .B3 (n_213), .O (n_222));
  AO12EHD g9187__5526(.A1 (n_236), .B1 (n_96), .B2 (n_64), .O (n_221));
  NR2BHD g9204__6783(.I1 (n_190), .I2 (n_212), .O (n_220));
  OAI12CHD g9210__3680(.A1 (n_211), .B1 (n_207), .B2
       (charge_timer[14]), .O (n_219));
  DBFRBEHD \charge_timer_reg[13] (.RB (rstz), .CKB (clk), .D (n_215),
       .Q (charge_timer[13]), .QB (UNCONNECTED8));
  ND2DHD g9209__1617(.I1 (charge_timer[14]), .I2 (n_210), .O (n_218));
  OAI22CHD g9212__2802(.A1 (n_133), .A2 (n_206), .B1 (n_130), .B2
       (n_129), .O (n_217));
  AOI12CHD g9191__1705(.A1 (state[2]), .B1 (n_216), .B2 (n_230), .O
       (n_236));
  DBFRBEHD \charge_timer_reg[12] (.RB (rstz), .CKB (clk), .D (n_209),
       .Q (charge_timer[12]), .QB (UNCONNECTED9));
  OAI22CHD g9213__5122(.A1 (n_208), .A2 (n_214), .B1
       (charge_timer[13]), .B2 (n_213), .O (n_215));
  OAI112BHD g9214__8246(.A1 (n_204), .B1 (n_169), .C1 (n_142), .C2
       (n_151), .O (n_212));
  INVCKDHD g9216(.I (n_210), .O (n_211));
  OAI13BHD g9220__7098(.A1 (n_205), .B1 (n_197), .B2
       (charge_timer[12]), .B3 (n_198), .O (n_209));
  OAI12CHD g9217__6131(.A1 (n_208), .B1 (n_207), .B2
       (charge_timer[13]), .O (n_210));
  MAO222CHD g9194__1881(.A1 (n_202), .B1 (n_12), .C1 (tbat[7]), .O
       (n_252));
  MAO222CHD g9196__5115(.A1 (n_201), .B1 (n_16), .C1 (tempmax[7]), .O
       (n_247));
  DBFRBEHD \charge_timer_reg[10] (.RB (rstz), .CKB (clk), .D (n_196),
       .Q (charge_timer[10]), .QB (UNCONNECTED10));
  DBFRBEHD \charge_timer_reg[11] (.RB (rstz), .CKB (clk), .D (n_199),
       .Q (charge_timer[11]), .QB (UNCONNECTED11));
  AOI222BHD g9226__7482(.A1 (n_132), .A2 (n_131), .B1 (n_194), .B2
       (n_128), .C1 (n_126), .C2 (n_127), .O (n_206));
  MAO222CHD g9199__4733(.A1 (n_195), .B1 (n_18), .C1 (vcutoff[7]), .O
       (n_216));
  ND2DHD g9222__6161(.I1 (charge_timer[12]), .I2 (n_203), .O (n_205));
  DBFRBEHD \charge_timer_reg[9] (.RB (rstz), .CKB (clk), .D (n_193), .Q
       (charge_timer[9]), .QB (UNCONNECTED12));
  MAOI1CHD g9225__9315(.A1 (n_56), .A2 (n_57), .B1 (n_189), .B2
       (n_187), .O (n_204));
  NR2CHD g9223__9945(.I1 (n_203), .I2 (n_106), .O (n_208));
  MAO222CHD g9207__2883(.A1 (n_184), .B1 (n_21), .C1 (tbat[6]), .O
       (n_202));
  MAO222CHD g9208__2346(.A1 (n_185), .B1 (n_9), .C1 (tempmax[6]), .O
       (n_201));
  NR3BHD g9219__1666(.I1 (n_213), .I2 (charge_timer[15]), .I3 (n_39),
       .O (n_200));
  OAI22CHD g9227__7410(.A1 (n_198), .A2 (charge_timer[11]), .B1
       (n_197), .B2 (n_191), .O (n_199));
  OAI13BHD g9231__6417(.A1 (n_188), .B1 (n_167), .B2 (n_40), .B3
       (n_192), .O (n_196));
  MAO222CHD g9215__5477(.A1 (n_177), .B1 (n_79), .C1 (vcutoff[6]), .O
       (n_195));
  DBFRBEHD \charge_timer_reg[8] (.RB (rstz), .CKB (clk), .D (n_186), .Q
       (charge_timer[8]), .QB (UNCONNECTED13));
  AO222EHD g9238__2398(.A1 (n_125), .A2 (n_124), .B1 (n_179), .B2
       (n_74), .C1 (n_172), .C2 (n_178), .O (n_194));
  OAI13BHD g9239__5107(.A1 (n_183), .B1 (n_173), .B2 (charge_timer[9]),
       .B3 (n_192), .O (n_193));
  OAI12CHD g9229__6260(.A1 (n_191), .B1 (n_207), .B2
       (charge_timer[11]), .O (n_203));
  OAI22CHD g9245__4319(.A1 (n_76), .A2 (n_189), .B1 (n_38), .B2
       (tmax[7]), .O (n_190));
  OR3B2CHD g9233__8428(.I1 (n_198), .B1 (charge_timer[12]), .B2
       (charge_timer[11]), .O (n_213));
  OAI12CHD g9235__5526(.A1 (charge_timer[10]), .B1 (n_107), .B2
       (n_182), .O (n_188));
  OAI112BHD g9236__6783(.A1 (n_176), .B1 (n_75), .C1 (charge_timer[7]),
       .C2 (tmax[7]), .O (n_187));
  OAI13BHD g9246__3680(.A1 (n_175), .B1 (n_155), .B2 (charge_timer[8]),
       .B3 (n_192), .O (n_186));
  MAO222CHD g9221__1617(.A1 (n_164), .B1 (n_1), .C1 (tempmax[5]), .O
       (n_185));
  DBFRBEHD \charge_timer_reg[7] (.RB (rstz), .CKB (clk), .D (n_174), .Q
       (charge_timer[7]), .QB (UNCONNECTED14));
  MAO222CHD g9228__2802(.A1 (n_168), .B1 (n_11), .C1 (tbat[5]), .O
       (n_184));
  ND2DHD g9242__1705(.I1 (charge_timer[9]), .I2 (n_182), .O (n_183));
  AOI12CHD g9241__5122(.A1 (n_261), .B1 (n_180), .B2 (n_181), .O
       (n_191));
  OR2EHD g9243__8246(.I1 (n_192), .I2 (n_180), .O (n_198));
  OR3B2CHD g9258__7098(.I1 (n_178), .B1 (n_171), .B2 (n_170), .O
       (n_179));
  MAO222CHD g9232__6131(.A1 (n_161), .B1 (n_14), .C1 (vcutoff[5]), .O
       (n_177));
  AO13EHD g9249__1881(.A1 (n_160), .B1 (charge_timer[3]), .B2 (n_83),
       .B3 (tmax[3]), .O (n_176));
  OAI12CHD g9248__5115(.A1 (charge_timer[8]), .B1 (n_156), .B2 (n_261),
       .O (n_175));
  OAI13BHD g9253__7482(.A1 (n_162), .B1 (n_135), .B2 (charge_timer[7]),
       .B3 (n_192), .O (n_174));
  AO12CHD g9250__4733(.A1 (n_261), .B1 (n_173), .B2 (n_181), .O
       (n_182));
  DBFRBEHD \charge_timer_reg[5] (.RB (rstz), .CKB (clk), .D (n_157), .Q
       (charge_timer[5]), .QB (UNCONNECTED15));
  ND2CHD g9259__6161(.I1 (n_171), .I2 (n_170), .O (n_172));
  AOI22BHD g9264__9315(.A1 (n_153), .A2 (n_139), .B1 (n_138), .B2
       (n_86), .O (n_169));
  OAI112BHD g9265__9945(.A1 (n_152), .B1 (n_102), .C1
       (charge_timer[8]), .C2 (n_101), .O (n_189));
  DBFRBEHD \charge_timer_reg[1] (.RB (rstz), .CKB (clk), .D (n_158), .Q
       (charge_timer[1]), .QB (UNCONNECTED16));
  DBFRBEHD \charge_timer_reg[6] (.RB (rstz), .CKB (clk), .D (n_163), .Q
       (charge_timer[6]), .QB (UNCONNECTED17));
  DBFRBEHD \charge_timer_reg[3] (.RB (rstz), .CKB (clk), .D (n_159), .Q
       (charge_timer[3]), .QB (UNCONNECTED18));
  MAO222CHD g9247__2883(.A1 (n_146), .B1 (n_25), .C1 (tbat[4]), .O
       (n_168));
  OR2EHD g9256__2346(.I1 (charge_timer[10]), .I2 (n_173), .O (n_167));
  OR3B2CHD g9255__1666(.I1 (n_173), .B1 (charge_timer[9]), .B2
       (charge_timer[10]), .O (n_180));
  AN4B1BHD g9234__7410(.I1 (n_148), .I2 (n_67), .I3 (n_33), .B1
       (n_165), .O (n_166));
  MAO222CHD g9240__6417(.A1 (n_147), .B1 (n_8), .C1 (tempmax[4]), .O
       (n_164));
  DBFRBEHD \charge_timer_reg[2] (.RB (rstz), .CKB (clk), .D (n_150), .Q
       (charge_timer[2]), .QB (UNCONNECTED19));
  DBFRBEHD \charge_timer_reg[4] (.RB (rstz), .CKB (clk), .D (n_154), .Q
       (charge_timer[4]), .QB (UNCONNECTED20));
  OAI13BHD g9261__5477(.A1 (n_149), .B1 (n_112), .B2 (charge_timer[6]),
       .B3 (n_192), .O (n_163));
  OAI12CHD g9257__2398(.A1 (charge_timer[7]), .B1 (n_136), .B2 (n_261),
       .O (n_162));
  MAO222CHD g9254__5107(.A1 (n_137), .B1 (n_62), .C1 (vcutoff[4]), .O
       (n_161));
  OAI22CHD g9262__6260(.A1 (n_84), .A2 (n_134), .B1 (n_89), .B2 (n_66),
       .O (n_160));
  OAI13BHD g9277__4319(.A1 (n_144), .B1 (n_51), .B2 (n_22), .B3
       (n_192), .O (n_159));
  OAI13BHD g9300__8428(.A1 (n_143), .B1 (n_118), .B2 (charge_timer[1]),
       .B3 (n_192), .O (n_158));
  OAI13BHD g9270__5526(.A1 (n_145), .B1 (n_78), .B2 (n_7), .B3 (n_192),
       .O (n_157));
  OAI222BHD g9273__6783(.A1 (n_140), .A2 (n_141), .B1 (n_243), .B2
       (vpreset[1]), .C1 (n_48), .C2 (state[0]), .O (n_171));
  AN2EHD g9266__3680(.I1 (n_155), .I2 (n_181), .O (n_156));
  DBFRBEHD \charge_timer_reg[0] (.RB (rstz), .CKB (clk), .D (n_119), .Q
       (charge_timer[0]), .QB (UNCONNECTED21));
  OR2B1CHD g9267__1617(.I1 (n_155), .B1 (charge_timer[8]), .O (n_173));
  OAI13BHD g9285__2802(.A1 (n_123), .B1 (n_98), .B2 (charge_timer[4]),
       .B3 (n_192), .O (n_154));
  OAI22CHD g9283__1705(.A1 (n_49), .A2 (n_117), .B1 (n_88), .B2 (n_87),
       .O (n_153));
  INVCKDHD g9281(.I (n_151), .O (n_152));
  OAI13BHD g9298__5122(.A1 (n_121), .B1 (n_99), .B2 (charge_timer[2]),
       .B3 (n_192), .O (n_150));
  OAI12CHD g9271__8246(.A1 (charge_timer[6]), .B1 (n_113), .B2 (n_261),
       .O (n_149));
  MAO222CHD g9263__7098(.A1 (n_109), .B1 (n_3), .C1 (iend[3]), .O
       (n_148));
  MAO222CHD g9252__6131(.A1 (n_114), .B1 (n_6), .C1 (tempmax[3]), .O
       (n_147));
  MAO222CHD g9274__1881(.A1 (n_110), .B1 (n_26), .C1 (tbat[3]), .O
       (n_146));
  OAI12CHD g9275__5115(.A1 (charge_timer[5]), .B1 (n_100), .B2 (n_122),
       .O (n_145));
  OAI12CHD g9291__7482(.A1 (charge_timer[3]), .B1 (n_104), .B2 (n_120),
       .O (n_144));
  OAI12CHD g9305__4733(.A1 (charge_timer[1]), .B1 (n_111), .B2 (n_261),
       .O (n_143));
  AOI22BHD g9284__6161(.A1 (charge_timer[8]), .A2 (n_103), .B1 (n_70),
       .B2 (n_71), .O (n_142));
  ND2DHD g9292__9315(.I1 (n_141), .I2 (n_140), .O (n_170));
  OAI112BHD g9288__9945(.A1 (n_139), .B1 (n_116), .C1 (n_115), .C2
       (n_41), .O (n_151));
  OAI22CHD g9282__2883(.A1 (n_108), .A2 (n_92), .B1 (n_55), .B2 (n_54),
       .O (n_138));
  MAO222CHD g9272__2346(.A1 (n_94), .B1 (n_61), .C1 (vcutoff[3]), .O
       (n_137));
  AN2EHD g9276__1666(.I1 (n_135), .I2 (n_181), .O (n_136));
  OAI112BHD g9286__7410(.A1 (n_93), .B1 (n_27), .C1 (charge_timer[2]),
       .C2 (tmax[2]), .O (n_134));
  OR2B1CHD g9278__6417(.I1 (n_135), .B1 (charge_timer[7]), .O (n_155));
  MOAI1CHD g9297__5477(.A1 (n_132), .A2 (n_131), .B1 (n_130), .B2
       (n_129), .O (n_133));
  OA22EHD g9296__2398(.A1 (n_127), .A2 (n_126), .B1 (n_125), .B2
       (n_124), .O (n_128));
  ND2CHD g9289__5107(.I1 (charge_timer[4]), .I2 (n_122), .O (n_123));
  ND2CHD g9304__6260(.I1 (charge_timer[2]), .I2 (n_120), .O (n_121));
  OAI22CHD g9308__4319(.A1 (n_192), .A2 (charge_timer[0]), .B1 (n_118),
       .B2 (n_257), .O (n_119));
  ND2DHD g9307__8428(.I1 (n_116), .I2 (n_115), .O (n_117));
  OAI112BHD g9310__5526(.A1 (n_81), .B1 (n_35), .C1 (n_69), .C2
       (vbat[0]), .O (n_141));
  MAO222CHD g9287__6783(.A1 (n_60), .B1 (n_4), .C1 (tempmax[2]), .O
       (n_114));
  AN2EHD g9290__3680(.I1 (n_112), .I2 (n_181), .O (n_113));
  NR2BHD g9341__1617(.I1 (charge_timer[0]), .I2 (n_207), .O (n_111));
  MAO222CHD g9299__2802(.A1 (n_59), .B1 (n_20), .C1 (tbat[2]), .O
       (n_110));
  MAO222CHD g9302__1705(.A1 (n_58), .B1 (n_13), .C1 (iend[2]), .O
       (n_109));
  AOI112BHD g9301__5122(.A1 (n_90), .B1 (n_85), .C1 (n_91), .C2
       (n_108), .O (n_139));
  OR2B1CHD g9294__8246(.I1 (n_112), .B1 (charge_timer[6]), .O (n_135));
  OAI112BHD g9293__7098(.A1 (vbat[6]), .B1 (vbat[7]), .C1 (n_63), .C2
       (vbat[5]), .O (n_230));
  NR2BHD g9333__6131(.I1 (charge_timer[9]), .I2 (n_207), .O (n_107));
  NR2BHD g9339__1881(.I1 (charge_timer[12]), .I2 (n_207), .O (n_106));
  AOI22BHD g9317__5115(.A1 (n_68), .A2 (iend[4]), .B1 (n_42), .B2
       (iend[5]), .O (n_105));
  NR2BHD g9337__7482(.I1 (charge_timer[2]), .I2 (n_207), .O (n_104));
  AN2EHD g9303__4733(.I1 (n_102), .I2 (n_101), .O (n_103));
  NR2BHD g9336__6161(.I1 (charge_timer[4]), .I2 (n_207), .O (n_100));
  AO12EHD g9322__9315(.A1 (n_261), .B1 (n_181), .B2 (n_99), .O (n_120));
  AO12EHD g9312__9945(.A1 (n_261), .B1 (n_181), .B2 (n_98), .O (n_122));
  AOI22BHD g9350__2883(.A1 (n_95), .A2 (vpreset[7]), .B1 (n_96), .B2
       (vbat[7]), .O (n_97));
  OAI22CHD g9352__2346(.A1 (vpreset[5]), .A2 (n_96), .B1 (n_95), .B2
       (vbat[5]), .O (n_131));
  OAI22CHD g9347__1666(.A1 (vpreset[1]), .A2 (n_96), .B1 (n_95), .B2
       (vbat[1]), .O (n_140));
  AOI22BHD g9353__7410(.A1 (n_95), .A2 (vpreset[4]), .B1 (n_96), .B2
       (vbat[4]), .O (n_127));
  AOI22BHD g9354__6417(.A1 (n_95), .A2 (vpreset[3]), .B1 (n_96), .B2
       (vbat[3]), .O (n_124));
  ND2DHD g9343__5477(.I1 (n_181), .I2 (n_257), .O (n_192));
  AOI22BHD g9311__2398(.A1 (n_50), .A2 (n_46), .B1 (n_15), .B2
       (vbat[2]), .O (n_94));
  AO222EHD g9309__5107(.A1 (charge_timer[2]), .A2 (tmax[2]), .B1
       (n_44), .B2 (tmax[0]), .C1 (charge_timer[1]), .C2 (tmax[1]), .O
       (n_93));
  OR2EHD g9306__6260(.I1 (n_91), .I2 (n_90), .O (n_92));
  AOI222BHD g9316__4319(.A1 (charge_timer[5]), .A2 (tmax[5]), .B1
       (charge_timer[4]), .B2 (n_53), .C1 (charge_timer[6]), .C2
       (tmax[6]), .O (n_89));
  AOI22BHD g9355__8428(.A1 (n_95), .A2 (vpreset[2]), .B1 (n_96), .B2
       (vbat[2]), .O (n_178));
  ND2CHD g9321__5526(.I1 (n_88), .I2 (n_87), .O (n_116));
  INVDHD g9314(.I (n_85), .O (n_86));
  INVDHD g9344(.I (n_83), .O (n_84));
  OR3B2CHD g9342__6783(.I1 (ibat[6]), .B1 (n_65), .B2 (iend[6]), .O
       (n_82));
  AOI22BHD g9345__3680(.A1 (n_95), .A2 (vbat[0]), .B1 (state[0]), .B2
       (vpreset[0]), .O (n_81));
  ND2DHD g9338__1617(.I1 (cv), .I2 (n_261), .O (n_80));
  MOAI1CHD g9349__2802(.A1 (n_95), .A2 (n_79), .B1 (n_95), .B2
       (vpreset[6]), .O (n_129));
  AO222EHD g9348__1705(.A1 (state[0]), .A2 (vpreset[3]), .B1 (n_95),
       .B2 (vbat[3]), .C1 (state[2]), .C2 (vcutoff[3]), .O (n_125));
  OR3B2CHD g9313__5122(.I1 (n_98), .B1 (charge_timer[5]), .B2
       (charge_timer[4]), .O (n_112));
  INVDHD g9357(.I (n_181), .O (n_207));
  OR2EHD g9315__8246(.I1 (charge_timer[5]), .I2 (n_98), .O (n_78));
  ND2DHD g9335__7098(.I1 (tc), .I2 (n_261), .O (n_77));
  AOI13BHD g9324__6131(.A1 (n_34), .B1 (charge_timer[7]), .B2 (n_75),
       .B3 (tmax[7]), .O (n_76));
  AO222EHD g9326__1881(.A1 (state[0]), .A2 (vpreset[2]), .B1 (n_95),
       .B2 (vbat[2]), .C1 (state[2]), .C2 (vcutoff[2]), .O (n_74));
  ND2DHD g9334__5115(.I1 (cc), .I2 (n_261), .O (n_73));
  AO222EHD g9331__7482(.A1 (state[2]), .A2 (vcutoff[7]), .B1 (n_95),
       .B2 (vbat[7]), .C1 (state[0]), .C2 (vpreset[7]), .O (n_72));
  AO222EHD g9328__4733(.A1 (state[2]), .A2 (vcutoff[5]), .B1 (n_95),
       .B2 (vbat[5]), .C1 (state[0]), .C2 (vpreset[5]), .O (n_132));
  AO222EHD g9329__6161(.A1 (state[2]), .A2 (vcutoff[4]), .B1 (n_95),
       .B2 (vbat[4]), .C1 (state[0]), .C2 (vpreset[4]), .O (n_126));
  AOI222BHD g9330__9315(.A1 (state[2]), .A2 (vcutoff[6]), .B1 (n_95),
       .B2 (vbat[6]), .C1 (state[0]), .C2 (vpreset[6]), .O (n_130));
  OR2EHD g9318__9945(.I1 (n_71), .I2 (n_70), .O (n_102));
  AN2EHD g9358__2883(.I1 (n_95), .I2 (vpreset[0]), .O (n_69));
  AN2B1CHD g9360__2346(.I1 (n_67), .B1 (ibat[4]), .O (n_68));
  NR3BHD g9351__1666(.I1 (n_28), .I2 (n_52), .I3 (n_66), .O (n_83));
  OAI12CHD g9362__7410(.A1 (n_108), .B1 (charge_timer[12]), .B2 (n_37),
       .O (n_88));
  OAI12CHD g9364__6417(.A1 (n_65), .B1 (n_10), .B2 (iend[6]), .O
       (n_165));
  AN2B1EHD g9365__5477(.I1 (state[2]), .B1 (n_64), .O (n_181));
  AOI12CHD g9340__2398(.A1 (n_62), .B1 (n_29), .B2 (n_61), .O (n_63));
  MAO222CHD g9327__5107(.A1 (n_36), .B1 (n_17), .C1 (tempmax[1]), .O
       (n_60));
  MAO222CHD g9325__6260(.A1 (n_31), .B1 (n_5), .C1 (tbat[1]), .O
       (n_59));
  MAO222CHD g9323__4319(.A1 (n_32), .B1 (n_19), .C1 (iend[1]), .O
       (n_58));
  NR2CHD g9320__8428(.I1 (n_57), .I2 (n_56), .O (n_85));
  AN2EHD g9319__5526(.I1 (n_55), .I2 (n_54), .O (n_90));
  AN2B1CHD g9359__6783(.I1 (tmax[4]), .B1 (n_52), .O (n_53));
  OR2EHD g9361__3680(.I1 (charge_timer[3]), .I2 (n_99), .O (n_51));
  OAI112BHD g9346__1617(.A1 (n_0), .B1 (vcutoff[0]), .C1 (n_47), .C2
       (vcutoff[1]), .O (n_50));
  AN2EHD g9363__2802(.I1 (n_49), .I2 (n_30), .O (n_70));
  OR3B2CHD g9356__1705(.I1 (n_99), .B1 (charge_timer[3]), .B2
       (charge_timer[2]), .O (n_98));
  MAOI1CHD g9370__5122(.A1 (n_244), .A2 (n_47), .B1 (vcutoff[1]), .B2
       (n_244), .O (n_48));
  AOI22BHD g9369__8246(.A1 (n_47), .A2 (vcutoff[1]), .B1 (n_2), .B2
       (vcutoff[2]), .O (n_46));
  OAI22CHD g9367__7098(.A1 (n_240), .A2 (state[2]), .B1 (n_244), .B2
       (state[1]), .O (n_45));
  OAI12CHD g9368__6131(.A1 (n_99), .B1 (n_118), .B2 (n_23), .O (n_44));
  INVDHD g9388(.I (n_95), .O (n_96));
  INVDHD g9366(.I (n_257), .O (n_261));
  OR2CHD g9380__1881(.I1 (iend[7]), .I2 (n_43), .O (n_65));
  MOAI1CHD g9372__5115(.A1 (charge_timer[11]), .A2 (tmax[3]), .B1
       (charge_timer[11]), .B2 (tmax[3]), .O (n_115));
  MOAI1CHD g9373__7482(.A1 (charge_timer[9]), .A2 (tmax[1]), .B1
       (charge_timer[9]), .B2 (tmax[1]), .O (n_101));
  MAOI1CHD g9374__4733(.A1 (charge_timer[14]), .A2 (tmax[6]), .B1
       (tmax[6]), .B2 (charge_timer[14]), .O (n_55));
  MAOI1CHD g9371__6161(.A1 (charge_timer[13]), .A2 (tmax[5]), .B1
       (tmax[5]), .B2 (charge_timer[13]), .O (n_91));
  OR2CHD g9379__9315(.I1 (iend[5]), .I2 (n_42), .O (n_67));
  AN4B1BHD g9375__9945(.I1 (en), .I2 (vtok), .I3 (dvdd), .B1 (dgnd), .O
       (n_257));
  INVDHD g9332(.I (n_49), .O (n_41));
  NR2CHD g9394__2883(.I1 (tmax[1]), .I2 (n_40), .O (n_71));
  ND2CHD g9399__2346(.I1 (state[0]), .I2 (n_240), .O (n_64));
  NR2CHD g9385__1666(.I1 (tmax[6]), .I2 (n_39), .O (n_56));
  ND2DHD g9382__7410(.I1 (n_38), .I2 (tmax[7]), .O (n_57));
  ND2CHD g9386__6417(.I1 (charge_timer[12]), .I2 (n_37), .O (n_108));
  AN2EHD g9401__5477(.I1 (n_244), .I2 (n_243), .O (n_95));
  OR2B1CHD g9378__2398(.I1 (tempmax[0]), .B1 (tbat[0]), .O (n_36));
  ND2CHD g9391__5107(.I1 (state[2]), .I2 (vcutoff[0]), .O (n_35));
  NR2CHD g9389__6260(.I1 (tmax[0]), .I2 (charge_timer[8]), .O (n_34));
  OR2B1CHD g9376__4319(.I1 (iend[4]), .B1 (ibat[4]), .O (n_33));
  OR2B1CHD g9383__8428(.I1 (iend[0]), .B1 (ibat[0]), .O (n_32));
  OR2B1CHD g9381__5526(.I1 (tbat[0]), .B1 (tempmin[0]), .O (n_31));
  OR2B1CHD g9384__6783(.I1 (tmax[3]), .B1 (charge_timer[11]), .O
       (n_87));
  OR2B1CHD g9387__3680(.I1 (tmax[2]), .B1 (charge_timer[10]), .O
       (n_49));
  OR2B1CHD g9377__1617(.I1 (charge_timer[10]), .B1 (tmax[2]), .O
       (n_30));
  ND2CHD g9392__2802(.I1 (vbat[2]), .I2 (vbat[1]), .O (n_29));
  NR2CHD g9393__1705(.I1 (tmax[4]), .I2 (charge_timer[4]), .O (n_28));
  OR2EHD g9390__5122(.I1 (tmax[3]), .I2 (charge_timer[3]), .O (n_27));
  ND2CHD g9397__8246(.I1 (charge_timer[8]), .I2 (tmax[0]), .O (n_75));
  NR2CHD g9396__7098(.I1 (tmax[6]), .I2 (charge_timer[6]), .O (n_66));
  OR2B1CHD g9395__6131(.I1 (tmax[5]), .B1 (charge_timer[13]), .O
       (n_54));
  NR2CHD g9398__1881(.I1 (tmax[5]), .I2 (charge_timer[5]), .O (n_52));
  ND2DHD g9400__5115(.I1 (charge_timer[1]), .I2 (charge_timer[0]), .O
       (n_99));
  INVCKDHD g9427(.I (tempmin[3]), .O (n_26));
  INVCKDHD g9402(.I (tempmin[4]), .O (n_25));
  INVCKDHD g9412(.I (cv), .O (vmonen));
  INVCKDHD g9416(.I (tmax[1]), .O (n_23));
  INVDHD g9440(.I (charge_timer[2]), .O (n_22));
  INVCKDHD g9404(.I (tempmin[6]), .O (n_21));
  INVCKDHD g9430(.I (tempmin[2]), .O (n_20));
  INVCKDHD g9428(.I (ibat[1]), .O (n_19));
  INVCKDHD g9437(.I (vbat[7]), .O (n_18));
  INVCKDHD g9435(.I (tbat[1]), .O (n_17));
  INVCKDHD g9436(.I (tbat[7]), .O (n_16));
  INVCKDHD g9432(.I (vcutoff[2]), .O (n_15));
  INVCKDHD g9420(.I (vbat[5]), .O (n_14));
  INVCKDHD g9429(.I (ibat[2]), .O (n_13));
  INVCKDHD g9417(.I (vbat[6]), .O (n_79));
  INVDHD g9421(.I (charge_timer[14]), .O (n_39));
  INVCKDHD g9438(.I (vbat[3]), .O (n_61));
  INVDHD g9422(.I (charge_timer[9]), .O (n_40));
  INVCKDHD g9439(.I (charge_timer[0]), .O (n_118));
  INVDHD g9443(.I (state[0]), .O (n_243));
  INVDHD g9444(.I (state[2]), .O (n_244));
  INVCKDHD g9425(.I (tempmin[7]), .O (n_12));
  INVCKDHD g9426(.I (tempmin[5]), .O (n_11));
  INVCKDHD g9405(.I (ibat[6]), .O (n_10));
  INVCKDHD g9431(.I (tbat[6]), .O (n_9));
  INVCKDHD g9409(.I (tbat[4]), .O (n_8));
  INVDHD g9441(.I (charge_timer[4]), .O (n_7));
  INVCKDHD g9411(.I (tbat[3]), .O (n_6));
  INVCKDHD g9403(.I (tempmin[1]), .O (n_5));
  INVCKDHD g9434(.I (tbat[2]), .O (n_4));
  INVCKDHD g9406(.I (ibat[3]), .O (n_3));
  INVCKDHD g9415(.I (vbat[2]), .O (n_2));
  INVCKDHD g9414(.I (tbat[5]), .O (n_1));
  INVCKDHD g9433(.I (vbat[0]), .O (n_0));
  INVCKDHD g9407(.I (ibat[5]), .O (n_42));
  INVCKDHD g9413(.I (tmax[4]), .O (n_37));
  INVDHD g9442(.I (charge_timer[13]), .O (n_214));
  INVCKDHD g9408(.I (ibat[7]), .O (n_43));
  INVDHD g9410(.I (charge_timer[15]), .O (n_38));
  INVDHD g9423(.I (charge_timer[11]), .O (n_197));
  INVCKDHD g9419(.I (vbat[4]), .O (n_62));
  INVCKDHD g9418(.I (vbat[1]), .O (n_47));
  INVDHD g9424(.I (state[1]), .O (n_240));
  TIE0DHD tie_0_cell(.O (so));
  TIE1DHD tie_1_cell(.O (logic_1_1_net));
endmodule

